# Generated by Django 3.1 on 2020-08-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.TextField(default='', max_length=200),
        ),
    ]
