# Generated by Django 3.1 on 2020-08-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='comments',
            field=models.TextField(default='Enter description or comments', max_length=200),
        ),
    ]
